name: Multi-Platform Build

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ] # Wyzwól, gdy wypchniesz tag, np. git push origin v1.0
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Wymagane, aby GitHub Action mógł stworzyć Release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    # Instalacja Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        arch: ${{ matrix.os == 'windows-latest' && 'win64_msvc2019_64' || 'gcc_64' }}

    # Zależności Linux
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev ninja-build

    # Zależności Windows
    - name: Setup Ninja (Windows)
      if: runner.os == 'Windows'
      uses: ashutoshvarma/setup-ninja@master

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # Budowanie
    - name: Configure CMake
      run: cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    # PAKOWANIE WINDOWS (ZIP)
    - name: Package Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        mkdir package
        copy build\PokemonFinder.exe package\
        windeployqt package\PokemonFinder.exe --no-translations
        
        if not exist package\cache mkdir package\cache
        
        # Pakujemy wszystko do pliku ZIP, żeby ładnie wyglądało w Releases
        powershell Compress-Archive -Path package\* -DestinationPath PokemonFinder-Windows.zip

    # PAKOWANIE LINUX (TAR.GZ)
    - name: Package Linux
      if: runner.os == 'Linux'
      run: |
        mkdir package
        cp build/PokemonFinder package/
        # chmod +x dla pewności, że plik jest wykonywalny
        chmod +x package/PokemonFinder
        # Pakujemy do tar.gz z zachowaniem uprawnień (p)
        tar -czpvf PokemonFinder-Linux.tar.gz -C package .
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          PokemonFinder-Windows.zip
          PokemonFinder-Linux.tar.gz

    # Opcjonalnie: Nadal wrzucamy artefakty dla zwykłych commitów (bez taga)
    - name: Upload Artifact
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v4
      with:
        name: PokemonFinder-${{ matrix.os }}
        path: package
